title: Nileena Davis
theme: jekyll-theme-minimal
description: Portfolio of Nileena Davis | Reporting Systems, Database Development, and Big Data Solutions
github_username: Nileena95  
show_downloads: true 
## Other Projects

| Repository Name                 | Description                                                                 |
|---------------------------------|-----------------------------------------------------------------------------|
| [Cardiac Risk Predictor](https://github.com/gsebastian11/Cardiac_Risk_Predictor_UI)| The Cardiac Risk Predictor is a software system that will predict the risk of heart disease based 
on various factors such as age, cholesterol level, and blood pressure and so on. The application 
utilizes machine learning techniques to analyze input data and generate predictions or risk assessment. The 
application presents the prediction or risk assessment to the user in a clear and understandable manner, such as 
displaying the risk level as low, moderate, or high.  

